name: rms
channels:
- bioconda
- conda-forge
- pkgs/main
dependencies:
- bioconductor-metaboannotation
- bioconductor-msbackendmsp
- ipykernel
- matchms
- nbformat
- numba
- pandas
- plotly
- python
- rdkit
- seaborn
- python-kaleido
- ms-entropy

